---

- name: Format disk
  become: yes
  filesystem:
    dev: "/dev/{{ item.dev }}"
    fstype: "{{ item.fstype }}"
  with_items: "{{ filesystems }}"
  when: filesystems is defined and (filesystems | length > 0)

- name: Mount disk
  become: yes
  mount:
    boot: yes
    fstype: "{{ item.fstype }}"
    path: "{{ item.mount_point }}"
    src: "/dev/{{ item.dev }}"
    state: mounted
  with_items: "{{ filesystems }}"
  when: filesystems is defined and (filesystems | length > 0)
