---

- name: Download the Logging Agent
  become: yes
  get_url:
    url: https://dl.google.com/cloudagents/install-logging-agent.sh
    dest: "/tmp/install-logging-agent.sh"
    mode: "+x"

- name: Install the Logging Agent
  become: yes
  shell: "/tmp/install-logging-agent.sh"

- name: Copy configuration file
  become: yes
  template:
    src: google-fluentd.conf.j2
    dest: "/etc/google-fluentd/google-fluentd.conf"
    backup: yes

- name: Create active configurations folder
  become: yes
  file:
    path: "{{ google_fluent_active_configs_path }}"
    state: directory

- name: Active configurations
  become: yes
  file:
    path: "{{ google_fluent_active_configs_path }}/{{ item }}.conf"
    src: "{{ google_fluent_configs_path }}/{{ item }}.conf"
    state: link
  with_items: "{{ google_fluent_active_configs }}"