---

# Entropy Configuration
- include: entropy.yml

# DNS Configuration
- include: dns.yml

# Drives Configuration
- include: disks.yml

# Hostname Configuration
- include: hostname.yml
  when: hostname_enabled

# Timezone
- include: timezone.yml
  when: timezone is defined and timezone != ""

# Automatic Upgrades
- include: automatic-upgrades.yml
